"@generated by @aspect_rules_js//npm/private:npm_translate_lock.bzl from pnpm lock file @com_github_scionproto_scion@com_github_scionproto_scion//rules_openapi/tools:pnpm-lock.yaml"

load("@aspect_rules_js//npm:npm_import.bzl", "npm_import")

def npm_repositories():
    "Generated npm_import repository rules corresponding to npm packages in @com_github_scionproto_scion@com_github_scionproto_scion//rules_openapi/tools:pnpm-lock.yaml"
    npm_import(
        name = "npm__at_redocly_ajv__8.6.4",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "@redocly/ajv",
        version = "8.6.4",
        integrity = "sha512-y9qNj0//tZtWB2jfXNK3BX18BSBp9zNR7KE7lMysVHwbZtY392OJCjm6Rb/h4UHH2r1AqjNEHFD6bRn+DqU9Mw==",
        deps = {
            "fast-deep-equal": "3.1.3",
            "json-schema-traverse": "1.0.0",
            "require-from-string": "2.0.2",
            "uri-js": "4.4.1",
        },
        transitive_closure = {
            "@redocly/ajv": ["8.6.4"],
            "fast-deep-equal": ["3.1.3"],
            "json-schema-traverse": ["1.0.0"],
            "require-from-string": ["2.0.2"],
            "uri-js": ["4.4.1"],
            "punycode": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__at_redocly_cli__1.0.0-beta.102",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {
            "rules_openapi/tools": ["@redocly/cli"],
        },
        package = "@redocly/cli",
        version = "1.0.0-beta.102",
        integrity = "sha512-jMLeyig4ZGj7A/HTo203r41qmTsYJpiiOGiFTo03OB84mRYuHUSADImZxPf9J8f2Vgwrei/zB56Tk+YaCd/b6A==",
        deps = {
            "@redocly/openapi-core": "1.0.0-beta.102",
            "assert-node-version": "1.0.3",
            "chokidar": "3.5.3",
            "colorette": "1.4.0",
            "glob": "7.2.3",
            "glob-promise": "3.4.0_glob@7.2.3",
            "handlebars": "4.7.7",
            "portfinder": "1.0.28",
            "simple-websocket": "9.1.0",
            "yargs": "17.0.1",
        },
        transitive_closure = {
            "@redocly/cli": ["1.0.0-beta.102"],
            "@redocly/openapi-core": ["1.0.0-beta.102"],
            "assert-node-version": ["1.0.3"],
            "chokidar": ["3.5.3"],
            "colorette": ["1.4.0"],
            "glob": ["7.2.3"],
            "glob-promise": ["3.4.0_glob@7.2.3"],
            "handlebars": ["4.7.7"],
            "portfinder": ["1.0.28"],
            "simple-websocket": ["9.1.0"],
            "yargs": ["17.0.1"],
            "cliui": ["7.0.4"],
            "escalade": ["3.1.1"],
            "get-caller-file": ["2.0.5"],
            "require-directory": ["2.1.1"],
            "string-width": ["4.2.3"],
            "y18n": ["5.0.8"],
            "yargs-parser": ["20.2.9"],
            "emoji-regex": ["8.0.0"],
            "is-fullwidth-code-point": ["3.0.0"],
            "strip-ansi": ["6.0.1"],
            "ansi-regex": ["5.0.1"],
            "wrap-ansi": ["7.0.0"],
            "ansi-styles": ["4.3.0"],
            "color-convert": ["2.0.1"],
            "color-name": ["1.1.4"],
            "debug": ["3.2.7", "4.3.4"],
            "queue-microtask": ["1.2.3"],
            "randombytes": ["2.1.0"],
            "readable-stream": ["3.6.0"],
            "ws": ["7.5.8"],
            "inherits": ["2.0.4"],
            "string_decoder": ["1.3.0"],
            "util-deprecate": ["1.0.2"],
            "safe-buffer": ["5.2.1"],
            "ms": ["2.1.3", "2.1.2"],
            "async": ["2.6.4"],
            "mkdirp": ["0.5.6"],
            "minimist": ["1.2.6"],
            "lodash": ["4.17.21"],
            "neo-async": ["2.6.2"],
            "source-map": ["0.6.1"],
            "wordwrap": ["1.0.0"],
            "uglify-js": ["3.16.0"],
            "@types/glob": ["7.2.0"],
            "@types/minimatch": ["3.0.5"],
            "@types/node": ["14.18.21"],
            "fs.realpath": ["1.0.0"],
            "inflight": ["1.0.6"],
            "minimatch": ["5.1.0", "3.1.2"],
            "once": ["1.4.0"],
            "path-is-absolute": ["1.0.1"],
            "wrappy": ["1.0.2"],
            "brace-expansion": ["2.0.1", "1.1.11"],
            "balanced-match": ["1.0.2"],
            "concat-map": ["0.0.1"],
            "anymatch": ["3.1.2"],
            "braces": ["3.0.2"],
            "glob-parent": ["5.1.2"],
            "is-binary-path": ["2.1.0"],
            "is-glob": ["4.0.3"],
            "normalize-path": ["3.0.0"],
            "readdirp": ["3.6.0"],
            "fsevents": ["2.3.2"],
            "picomatch": ["2.3.1"],
            "is-extglob": ["2.1.1"],
            "binary-extensions": ["2.2.0"],
            "fill-range": ["7.0.1"],
            "to-regex-range": ["5.0.1"],
            "is-number": ["7.0.0"],
            "expected-node-version": ["1.0.2"],
            "semver": ["5.7.1"],
            "@redocly/ajv": ["8.6.4"],
            "js-levenshtein": ["1.1.6"],
            "js-yaml": ["4.1.0"],
            "lodash.isequal": ["4.5.0"],
            "node-fetch": ["2.6.7"],
            "pluralize": ["8.0.0"],
            "yaml-ast-parser": ["0.0.43"],
            "whatwg-url": ["5.0.0"],
            "tr46": ["0.0.3"],
            "webidl-conversions": ["3.0.1"],
            "argparse": ["2.0.1"],
            "fast-deep-equal": ["3.1.3"],
            "json-schema-traverse": ["1.0.0"],
            "require-from-string": ["2.0.2"],
            "uri-js": ["4.4.1"],
            "punycode": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__at_redocly_openapi-core__1.0.0-beta.102",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "@redocly/openapi-core",
        version = "1.0.0-beta.102",
        integrity = "sha512-3Fr3fg+9VEF4+4uoyvOOk+9ipmX2GYhlb18uZbpC4v3cUgGpkTRGZM2Qetfah7Tgx2LgqLuw8A1icDD6Zed2Gw==",
        deps = {
            "@redocly/ajv": "8.6.4",
            "@types/node": "14.18.21",
            "colorette": "1.4.0",
            "js-levenshtein": "1.1.6",
            "js-yaml": "4.1.0",
            "lodash.isequal": "4.5.0",
            "minimatch": "5.1.0",
            "node-fetch": "2.6.7",
            "pluralize": "8.0.0",
            "yaml-ast-parser": "0.0.43",
        },
        transitive_closure = {
            "@redocly/openapi-core": ["1.0.0-beta.102"],
            "@redocly/ajv": ["8.6.4"],
            "@types/node": ["14.18.21"],
            "colorette": ["1.4.0"],
            "js-levenshtein": ["1.1.6"],
            "js-yaml": ["4.1.0"],
            "lodash.isequal": ["4.5.0"],
            "minimatch": ["5.1.0"],
            "node-fetch": ["2.6.7"],
            "pluralize": ["8.0.0"],
            "yaml-ast-parser": ["0.0.43"],
            "whatwg-url": ["5.0.0"],
            "tr46": ["0.0.3"],
            "webidl-conversions": ["3.0.1"],
            "brace-expansion": ["2.0.1"],
            "balanced-match": ["1.0.2"],
            "argparse": ["2.0.1"],
            "fast-deep-equal": ["3.1.3"],
            "json-schema-traverse": ["1.0.0"],
            "require-from-string": ["2.0.2"],
            "uri-js": ["4.4.1"],
            "punycode": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__at_types_glob__7.2.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "@types/glob",
        version = "7.2.0",
        integrity = "sha512-ZUxbzKl0IfJILTS6t7ip5fQQM/J3TJYubDm3nMbgubNNYS62eXeUpoLUC8/7fJNiFYHTrGPQn7hspDUzIHX3UA==",
        deps = {
            "@types/minimatch": "3.0.5",
            "@types/node": "14.18.21",
        },
        transitive_closure = {
            "@types/glob": ["7.2.0"],
            "@types/minimatch": ["3.0.5"],
            "@types/node": ["14.18.21"],
        },
    )

    npm_import(
        name = "npm__at_types_minimatch__3.0.5",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "@types/minimatch",
        version = "3.0.5",
        integrity = "sha512-Klz949h02Gz2uZCMGwDUSDS1YBlTdDDgbWHi+81l29tQALUtvz4rAYi5uoVhE5Lagoq6DeqAUlbrHvW/mXDgdQ==",
        transitive_closure = {
            "@types/minimatch": ["3.0.5"],
        },
    )

    npm_import(
        name = "npm__at_types_node__14.18.21",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "@types/node",
        version = "14.18.21",
        integrity = "sha512-x5W9s+8P4XteaxT/jKF0PSb7XEvo5VmqEWgsMlyeY4ZlLK8I6aH6g5TPPyDlLAep+GYf4kefb7HFyc7PAO3m+Q==",
        transitive_closure = {
            "@types/node": ["14.18.21"],
        },
    )

    npm_import(
        name = "npm__ansi-regex__5.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "ansi-regex",
        version = "5.0.1",
        integrity = "sha512-quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==",
        transitive_closure = {
            "ansi-regex": ["5.0.1"],
        },
    )

    npm_import(
        name = "npm__ansi-styles__4.3.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "ansi-styles",
        version = "4.3.0",
        integrity = "sha512-zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==",
        deps = {
            "color-convert": "2.0.1",
        },
        transitive_closure = {
            "ansi-styles": ["4.3.0"],
            "color-convert": ["2.0.1"],
            "color-name": ["1.1.4"],
        },
    )

    npm_import(
        name = "npm__anymatch__3.1.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "anymatch",
        version = "3.1.2",
        integrity = "sha512-P43ePfOAIupkguHUycrc4qJ9kz8ZiuOUijaETwX7THt0Y/GNK7v0aa8rY816xWjZ7rJdA5XdMcpVFTKMq+RvWg==",
        deps = {
            "normalize-path": "3.0.0",
            "picomatch": "2.3.1",
        },
        transitive_closure = {
            "anymatch": ["3.1.2"],
            "normalize-path": ["3.0.0"],
            "picomatch": ["2.3.1"],
        },
    )

    npm_import(
        name = "npm__argparse__2.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "argparse",
        version = "2.0.1",
        integrity = "sha512-8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==",
        transitive_closure = {
            "argparse": ["2.0.1"],
        },
    )

    npm_import(
        name = "npm__assert-node-version__1.0.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "assert-node-version",
        version = "1.0.3",
        integrity = "sha512-XcKBGJ1t0RrCcus9dQX57FER4PTEz/+Tee2jj+EdFIGyw5j8hwDNXZzgRYLQ916twVjSuA47adrZsSxLbpEX9A==",
        deps = {
            "expected-node-version": "1.0.2",
            "semver": "5.7.1",
        },
        transitive_closure = {
            "assert-node-version": ["1.0.3"],
            "expected-node-version": ["1.0.2"],
            "semver": ["5.7.1"],
        },
    )

    npm_import(
        name = "npm__async__2.6.4",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "async",
        version = "2.6.4",
        integrity = "sha512-mzo5dfJYwAn29PeiJ0zvwTo04zj8HDJj0Mn8TD7sno7q12prdbnasKJHhkm2c1LgrhlJ0teaea8860oxi51mGA==",
        deps = {
            "lodash": "4.17.21",
        },
        transitive_closure = {
            "async": ["2.6.4"],
            "lodash": ["4.17.21"],
        },
    )

    npm_import(
        name = "npm__balanced-match__1.0.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "balanced-match",
        version = "1.0.2",
        integrity = "sha512-3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==",
        transitive_closure = {
            "balanced-match": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__binary-extensions__2.2.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "binary-extensions",
        version = "2.2.0",
        integrity = "sha512-jDctJ/IVQbZoJykoeHbhXpOlNBqGNcwXJKJog42E5HDPUwQTSdjCHdihjj0DlnheQ7blbT6dHOafNAiS8ooQKA==",
        transitive_closure = {
            "binary-extensions": ["2.2.0"],
        },
    )

    npm_import(
        name = "npm__brace-expansion__1.1.11",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "brace-expansion",
        version = "1.1.11",
        integrity = "sha512-iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==",
        deps = {
            "balanced-match": "1.0.2",
            "concat-map": "0.0.1",
        },
        transitive_closure = {
            "brace-expansion": ["1.1.11"],
            "balanced-match": ["1.0.2"],
            "concat-map": ["0.0.1"],
        },
    )

    npm_import(
        name = "npm__brace-expansion__2.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "brace-expansion",
        version = "2.0.1",
        integrity = "sha512-XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==",
        deps = {
            "balanced-match": "1.0.2",
        },
        transitive_closure = {
            "brace-expansion": ["2.0.1"],
            "balanced-match": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__braces__3.0.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "braces",
        version = "3.0.2",
        integrity = "sha512-b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==",
        deps = {
            "fill-range": "7.0.1",
        },
        transitive_closure = {
            "braces": ["3.0.2"],
            "fill-range": ["7.0.1"],
            "to-regex-range": ["5.0.1"],
            "is-number": ["7.0.0"],
        },
    )

    npm_import(
        name = "npm__chokidar__3.5.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "chokidar",
        version = "3.5.3",
        integrity = "sha512-Dr3sfKRP6oTcjf2JmUmFJfeVMvXBdegxB0iVQ5eb2V10uFJUCAS8OByZdVAyVb8xXNz3GjjTgj9kLWsZTqE6kw==",
        deps = {
            "fsevents": "2.3.2",
            "anymatch": "3.1.2",
            "braces": "3.0.2",
            "glob-parent": "5.1.2",
            "is-binary-path": "2.1.0",
            "is-glob": "4.0.3",
            "normalize-path": "3.0.0",
            "readdirp": "3.6.0",
        },
        transitive_closure = {
            "chokidar": ["3.5.3"],
            "anymatch": ["3.1.2"],
            "braces": ["3.0.2"],
            "glob-parent": ["5.1.2"],
            "is-binary-path": ["2.1.0"],
            "is-glob": ["4.0.3"],
            "normalize-path": ["3.0.0"],
            "readdirp": ["3.6.0"],
            "fsevents": ["2.3.2"],
            "picomatch": ["2.3.1"],
            "is-extglob": ["2.1.1"],
            "binary-extensions": ["2.2.0"],
            "fill-range": ["7.0.1"],
            "to-regex-range": ["5.0.1"],
            "is-number": ["7.0.0"],
        },
    )

    npm_import(
        name = "npm__cliui__7.0.4",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "cliui",
        version = "7.0.4",
        integrity = "sha512-OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==",
        deps = {
            "string-width": "4.2.3",
            "strip-ansi": "6.0.1",
            "wrap-ansi": "7.0.0",
        },
        transitive_closure = {
            "cliui": ["7.0.4"],
            "string-width": ["4.2.3"],
            "strip-ansi": ["6.0.1"],
            "wrap-ansi": ["7.0.0"],
            "ansi-styles": ["4.3.0"],
            "color-convert": ["2.0.1"],
            "color-name": ["1.1.4"],
            "ansi-regex": ["5.0.1"],
            "emoji-regex": ["8.0.0"],
            "is-fullwidth-code-point": ["3.0.0"],
        },
    )

    npm_import(
        name = "npm__color-convert__2.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "color-convert",
        version = "2.0.1",
        integrity = "sha512-RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==",
        deps = {
            "color-name": "1.1.4",
        },
        transitive_closure = {
            "color-convert": ["2.0.1"],
            "color-name": ["1.1.4"],
        },
    )

    npm_import(
        name = "npm__color-name__1.1.4",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "color-name",
        version = "1.1.4",
        integrity = "sha512-dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==",
        transitive_closure = {
            "color-name": ["1.1.4"],
        },
    )

    npm_import(
        name = "npm__colorette__1.4.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "colorette",
        version = "1.4.0",
        integrity = "sha512-Y2oEozpomLn7Q3HFP7dpww7AtMJplbM9lGZP6RDfHqmbeRjiwRg4n6VM6j4KLmRke85uWEI7JqF17f3pqdRA0g==",
        transitive_closure = {
            "colorette": ["1.4.0"],
        },
    )

    npm_import(
        name = "npm__concat-map__0.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "concat-map",
        version = "0.0.1",
        integrity = "sha512-/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==",
        transitive_closure = {
            "concat-map": ["0.0.1"],
        },
    )

    npm_import(
        name = "npm__debug__3.2.7",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "debug",
        version = "3.2.7",
        integrity = "sha512-CFjzYYAi4ThfiQvizrFQevTTXHtnCqWfe7x1AhgEscTz6ZbLbfoLRLPugTQyBth6f8ZERVUSyWHFD/7Wu4t1XQ==",
        deps = {
            "ms": "2.1.3",
        },
        transitive_closure = {
            "debug": ["3.2.7"],
            "ms": ["2.1.3"],
        },
    )

    npm_import(
        name = "npm__debug__4.3.4",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "debug",
        version = "4.3.4",
        integrity = "sha512-PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==",
        deps = {
            "ms": "2.1.2",
        },
        transitive_closure = {
            "debug": ["4.3.4"],
            "ms": ["2.1.2"],
        },
    )

    npm_import(
        name = "npm__emoji-regex__8.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "emoji-regex",
        version = "8.0.0",
        integrity = "sha512-MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==",
        transitive_closure = {
            "emoji-regex": ["8.0.0"],
        },
    )

    npm_import(
        name = "npm__escalade__3.1.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "escalade",
        version = "3.1.1",
        integrity = "sha512-k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==",
        transitive_closure = {
            "escalade": ["3.1.1"],
        },
    )

    npm_import(
        name = "npm__expected-node-version__1.0.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "expected-node-version",
        version = "1.0.2",
        integrity = "sha512-OSaCdgF02srujDqJz1JWGpqk8Rq3uNYHLmtpBHJrZN3BvuMvzijJMqRVxZN1qLJtKVwjXhmOp+lfsRUqx8n54w==",
        transitive_closure = {
            "expected-node-version": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__fast-deep-equal__3.1.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "fast-deep-equal",
        version = "3.1.3",
        integrity = "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==",
        transitive_closure = {
            "fast-deep-equal": ["3.1.3"],
        },
    )

    npm_import(
        name = "npm__fill-range__7.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "fill-range",
        version = "7.0.1",
        integrity = "sha512-qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==",
        deps = {
            "to-regex-range": "5.0.1",
        },
        transitive_closure = {
            "fill-range": ["7.0.1"],
            "to-regex-range": ["5.0.1"],
            "is-number": ["7.0.0"],
        },
    )

    npm_import(
        name = "npm__fs.realpath__1.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "fs.realpath",
        version = "1.0.0",
        integrity = "sha512-OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==",
        transitive_closure = {
            "fs.realpath": ["1.0.0"],
        },
    )

    npm_import(
        name = "npm__fsevents__2.3.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "fsevents",
        version = "2.3.2",
        integrity = "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==",
        transitive_closure = {
            "fsevents": ["2.3.2"],
        },
        run_lifecycle_hooks = True,
    )

    npm_import(
        name = "npm__get-caller-file__2.0.5",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "get-caller-file",
        version = "2.0.5",
        integrity = "sha512-DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==",
        transitive_closure = {
            "get-caller-file": ["2.0.5"],
        },
    )

    npm_import(
        name = "npm__glob-parent__5.1.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "glob-parent",
        version = "5.1.2",
        integrity = "sha512-AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==",
        deps = {
            "is-glob": "4.0.3",
        },
        transitive_closure = {
            "glob-parent": ["5.1.2"],
            "is-glob": ["4.0.3"],
            "is-extglob": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__glob-promise__3.4.0__glob_7.2.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "glob-promise",
        version = "3.4.0_glob@7.2.3",
        integrity = "sha512-q08RJ6O+eJn+dVanerAndJwIcumgbDdYiUT7zFQl3Wm1xD6fBKtah7H8ZJChj4wP+8C+QfeVy8xautR7rdmKEw==",
        deps = {
            "@types/glob": "7.2.0",
            "glob": "7.2.3",
        },
        transitive_closure = {
            "glob-promise": ["3.4.0_glob@7.2.3"],
            "@types/glob": ["7.2.0"],
            "glob": ["7.2.3"],
            "fs.realpath": ["1.0.0"],
            "inflight": ["1.0.6"],
            "inherits": ["2.0.4"],
            "minimatch": ["3.1.2"],
            "once": ["1.4.0"],
            "path-is-absolute": ["1.0.1"],
            "wrappy": ["1.0.2"],
            "brace-expansion": ["1.1.11"],
            "balanced-match": ["1.0.2"],
            "concat-map": ["0.0.1"],
            "@types/minimatch": ["3.0.5"],
            "@types/node": ["14.18.21"],
        },
    )

    npm_import(
        name = "npm__glob__7.2.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "glob",
        version = "7.2.3",
        integrity = "sha512-nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==",
        deps = {
            "fs.realpath": "1.0.0",
            "inflight": "1.0.6",
            "inherits": "2.0.4",
            "minimatch": "3.1.2",
            "once": "1.4.0",
            "path-is-absolute": "1.0.1",
        },
        transitive_closure = {
            "glob": ["7.2.3"],
            "fs.realpath": ["1.0.0"],
            "inflight": ["1.0.6"],
            "inherits": ["2.0.4"],
            "minimatch": ["3.1.2"],
            "once": ["1.4.0"],
            "path-is-absolute": ["1.0.1"],
            "wrappy": ["1.0.2"],
            "brace-expansion": ["1.1.11"],
            "balanced-match": ["1.0.2"],
            "concat-map": ["0.0.1"],
        },
    )

    npm_import(
        name = "npm__handlebars__4.7.7",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "handlebars",
        version = "4.7.7",
        integrity = "sha512-aAcXm5OAfE/8IXkcZvCepKU3VzW1/39Fb5ZuqMtgI/hT8X2YgoMvBY5dLhq/cpOvw7Lk1nK/UF71aLG/ZnVYRA==",
        deps = {
            "uglify-js": "3.16.0",
            "minimist": "1.2.6",
            "neo-async": "2.6.2",
            "source-map": "0.6.1",
            "wordwrap": "1.0.0",
        },
        transitive_closure = {
            "handlebars": ["4.7.7"],
            "minimist": ["1.2.6"],
            "neo-async": ["2.6.2"],
            "source-map": ["0.6.1"],
            "wordwrap": ["1.0.0"],
            "uglify-js": ["3.16.0"],
        },
    )

    npm_import(
        name = "npm__inflight__1.0.6",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "inflight",
        version = "1.0.6",
        integrity = "sha512-k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==",
        deps = {
            "once": "1.4.0",
            "wrappy": "1.0.2",
        },
        transitive_closure = {
            "inflight": ["1.0.6"],
            "once": ["1.4.0"],
            "wrappy": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__inherits__2.0.4",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "inherits",
        version = "2.0.4",
        integrity = "sha512-k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==",
        transitive_closure = {
            "inherits": ["2.0.4"],
        },
    )

    npm_import(
        name = "npm__is-binary-path__2.1.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "is-binary-path",
        version = "2.1.0",
        integrity = "sha512-ZMERYes6pDydyuGidse7OsHxtbI7WVeUEozgR/g7rd0xUimYNlvZRE/K2MgZTjWy725IfelLeVcEM97mmtRGXw==",
        deps = {
            "binary-extensions": "2.2.0",
        },
        transitive_closure = {
            "is-binary-path": ["2.1.0"],
            "binary-extensions": ["2.2.0"],
        },
    )

    npm_import(
        name = "npm__is-extglob__2.1.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "is-extglob",
        version = "2.1.1",
        integrity = "sha512-SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==",
        transitive_closure = {
            "is-extglob": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__is-fullwidth-code-point__3.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "is-fullwidth-code-point",
        version = "3.0.0",
        integrity = "sha512-zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==",
        transitive_closure = {
            "is-fullwidth-code-point": ["3.0.0"],
        },
    )

    npm_import(
        name = "npm__is-glob__4.0.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "is-glob",
        version = "4.0.3",
        integrity = "sha512-xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==",
        deps = {
            "is-extglob": "2.1.1",
        },
        transitive_closure = {
            "is-glob": ["4.0.3"],
            "is-extglob": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__is-number__7.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "is-number",
        version = "7.0.0",
        integrity = "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==",
        transitive_closure = {
            "is-number": ["7.0.0"],
        },
    )

    npm_import(
        name = "npm__js-levenshtein__1.1.6",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "js-levenshtein",
        version = "1.1.6",
        integrity = "sha512-X2BB11YZtrRqY4EnQcLX5Rh373zbK4alC1FW7D7MBhL2gtcC17cTnr6DmfHZeS0s2rTHjUTMMHfG7gO8SSdw+g==",
        transitive_closure = {
            "js-levenshtein": ["1.1.6"],
        },
    )

    npm_import(
        name = "npm__js-yaml__4.1.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "js-yaml",
        version = "4.1.0",
        integrity = "sha512-wpxZs9NoxZaJESJGIZTyDEaYpl0FKSA+FB9aJiyemKhMwkxQg63h4T1KJgUGHpTqPDNRcmmYLugrRjJlBtWvRA==",
        deps = {
            "argparse": "2.0.1",
        },
        transitive_closure = {
            "js-yaml": ["4.1.0"],
            "argparse": ["2.0.1"],
        },
    )

    npm_import(
        name = "npm__json-schema-traverse__1.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "json-schema-traverse",
        version = "1.0.0",
        integrity = "sha512-NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==",
        transitive_closure = {
            "json-schema-traverse": ["1.0.0"],
        },
    )

    npm_import(
        name = "npm__lodash.isequal__4.5.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "lodash.isequal",
        version = "4.5.0",
        integrity = "sha512-pDo3lu8Jhfjqls6GkMgpahsF9kCyayhgykjyLMNFTKWrpVdAQtYyB4muAMWozBB4ig/dtWAmsMxLEI8wuz+DYQ==",
        transitive_closure = {
            "lodash.isequal": ["4.5.0"],
        },
    )

    npm_import(
        name = "npm__lodash__4.17.21",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "lodash",
        version = "4.17.21",
        integrity = "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==",
        transitive_closure = {
            "lodash": ["4.17.21"],
        },
    )

    npm_import(
        name = "npm__minimatch__3.1.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "minimatch",
        version = "3.1.2",
        integrity = "sha512-J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==",
        deps = {
            "brace-expansion": "1.1.11",
        },
        transitive_closure = {
            "minimatch": ["3.1.2"],
            "brace-expansion": ["1.1.11"],
            "balanced-match": ["1.0.2"],
            "concat-map": ["0.0.1"],
        },
    )

    npm_import(
        name = "npm__minimatch__5.1.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "minimatch",
        version = "5.1.0",
        integrity = "sha512-9TPBGGak4nHfGZsPBohm9AWg6NoT7QTCehS3BIJABslyZbzxfV78QM2Y6+i741OPZIafFAaiiEMh5OyIrJPgtg==",
        deps = {
            "brace-expansion": "2.0.1",
        },
        transitive_closure = {
            "minimatch": ["5.1.0"],
            "brace-expansion": ["2.0.1"],
            "balanced-match": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__minimist__1.2.6",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "minimist",
        version = "1.2.6",
        integrity = "sha512-Jsjnk4bw3YJqYzbdyBiNsPWHPfO++UGG749Cxs6peCu5Xg4nrena6OVxOYxrQTqww0Jmwt+Ref8rggumkTLz9Q==",
        transitive_closure = {
            "minimist": ["1.2.6"],
        },
    )

    npm_import(
        name = "npm__mkdirp__0.5.6",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "mkdirp",
        version = "0.5.6",
        integrity = "sha512-FP+p8RB8OWpF3YZBCrP5gtADmtXApB5AMLn+vdyA+PyxCjrCs00mjyUozssO33cwDeT3wNGdLxJ5M//YqtHAJw==",
        deps = {
            "minimist": "1.2.6",
        },
        transitive_closure = {
            "mkdirp": ["0.5.6"],
            "minimist": ["1.2.6"],
        },
    )

    npm_import(
        name = "npm__ms__2.1.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "ms",
        version = "2.1.2",
        integrity = "sha512-sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==",
        transitive_closure = {
            "ms": ["2.1.2"],
        },
    )

    npm_import(
        name = "npm__ms__2.1.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "ms",
        version = "2.1.3",
        integrity = "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==",
        transitive_closure = {
            "ms": ["2.1.3"],
        },
    )

    npm_import(
        name = "npm__neo-async__2.6.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "neo-async",
        version = "2.6.2",
        integrity = "sha512-Yd3UES5mWCSqR+qNT93S3UoYUkqAZ9lLg8a7g9rimsWmYGK8cVToA4/sF3RrshdyV3sAGMXVUmpMYOw+dLpOuw==",
        transitive_closure = {
            "neo-async": ["2.6.2"],
        },
    )

    npm_import(
        name = "npm__node-fetch__2.6.7",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "node-fetch",
        version = "2.6.7",
        integrity = "sha512-ZjMPFEfVx5j+y2yF35Kzx5sF7kDzxuDj6ziH4FFbOp87zKDZNx8yExJIb05OGF4Nlt9IHFIMBkRl41VdvcNdbQ==",
        deps = {
            "whatwg-url": "5.0.0",
        },
        transitive_closure = {
            "node-fetch": ["2.6.7"],
            "whatwg-url": ["5.0.0"],
            "tr46": ["0.0.3"],
            "webidl-conversions": ["3.0.1"],
        },
    )

    npm_import(
        name = "npm__normalize-path__3.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "normalize-path",
        version = "3.0.0",
        integrity = "sha512-6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==",
        transitive_closure = {
            "normalize-path": ["3.0.0"],
        },
    )

    npm_import(
        name = "npm__once__1.4.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "once",
        version = "1.4.0",
        integrity = "sha512-lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==",
        deps = {
            "wrappy": "1.0.2",
        },
        transitive_closure = {
            "once": ["1.4.0"],
            "wrappy": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__path-is-absolute__1.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "path-is-absolute",
        version = "1.0.1",
        integrity = "sha512-AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==",
        transitive_closure = {
            "path-is-absolute": ["1.0.1"],
        },
    )

    npm_import(
        name = "npm__picomatch__2.3.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "picomatch",
        version = "2.3.1",
        integrity = "sha512-JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==",
        transitive_closure = {
            "picomatch": ["2.3.1"],
        },
    )

    npm_import(
        name = "npm__pluralize__8.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "pluralize",
        version = "8.0.0",
        integrity = "sha512-Nc3IT5yHzflTfbjgqWcCPpo7DaKy4FnpB0l/zCAW0Tc7jxAiuqSxHasntB3D7887LSrA93kDJ9IXovxJYxyLCA==",
        transitive_closure = {
            "pluralize": ["8.0.0"],
        },
    )

    npm_import(
        name = "npm__portfinder__1.0.28",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "portfinder",
        version = "1.0.28",
        integrity = "sha512-Se+2isanIcEqf2XMHjyUKskczxbPH7dQnlMjXX6+dybayyHvAf/TCgyMRlzf/B6QDhAEFOGes0pzRo3by4AbMA==",
        deps = {
            "async": "2.6.4",
            "debug": "3.2.7",
            "mkdirp": "0.5.6",
        },
        transitive_closure = {
            "portfinder": ["1.0.28"],
            "async": ["2.6.4"],
            "debug": ["3.2.7"],
            "mkdirp": ["0.5.6"],
            "minimist": ["1.2.6"],
            "ms": ["2.1.3"],
            "lodash": ["4.17.21"],
        },
    )

    npm_import(
        name = "npm__punycode__2.1.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "punycode",
        version = "2.1.1",
        integrity = "sha512-XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==",
        transitive_closure = {
            "punycode": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__queue-microtask__1.2.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "queue-microtask",
        version = "1.2.3",
        integrity = "sha512-NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==",
        transitive_closure = {
            "queue-microtask": ["1.2.3"],
        },
    )

    npm_import(
        name = "npm__randombytes__2.1.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "randombytes",
        version = "2.1.0",
        integrity = "sha512-vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==",
        deps = {
            "safe-buffer": "5.2.1",
        },
        transitive_closure = {
            "randombytes": ["2.1.0"],
            "safe-buffer": ["5.2.1"],
        },
    )

    npm_import(
        name = "npm__readable-stream__3.6.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "readable-stream",
        version = "3.6.0",
        integrity = "sha512-BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==",
        deps = {
            "inherits": "2.0.4",
            "string_decoder": "1.3.0",
            "util-deprecate": "1.0.2",
        },
        transitive_closure = {
            "readable-stream": ["3.6.0"],
            "inherits": ["2.0.4"],
            "string_decoder": ["1.3.0"],
            "util-deprecate": ["1.0.2"],
            "safe-buffer": ["5.2.1"],
        },
    )

    npm_import(
        name = "npm__readdirp__3.6.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "readdirp",
        version = "3.6.0",
        integrity = "sha512-hOS089on8RduqdbhvQ5Z37A0ESjsqz6qnRcffsMU3495FuTdqSm+7bhJ29JvIOsBDEEnan5DPu9t3To9VRlMzA==",
        deps = {
            "picomatch": "2.3.1",
        },
        transitive_closure = {
            "readdirp": ["3.6.0"],
            "picomatch": ["2.3.1"],
        },
    )

    npm_import(
        name = "npm__require-directory__2.1.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "require-directory",
        version = "2.1.1",
        integrity = "sha512-fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==",
        transitive_closure = {
            "require-directory": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__require-from-string__2.0.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "require-from-string",
        version = "2.0.2",
        integrity = "sha512-Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==",
        transitive_closure = {
            "require-from-string": ["2.0.2"],
        },
    )

    npm_import(
        name = "npm__safe-buffer__5.2.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "safe-buffer",
        version = "5.2.1",
        integrity = "sha512-rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==",
        transitive_closure = {
            "safe-buffer": ["5.2.1"],
        },
    )

    npm_import(
        name = "npm__semver__5.7.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "semver",
        version = "5.7.1",
        integrity = "sha512-sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==",
        transitive_closure = {
            "semver": ["5.7.1"],
        },
    )

    npm_import(
        name = "npm__simple-websocket__9.1.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "simple-websocket",
        version = "9.1.0",
        integrity = "sha512-8MJPnjRN6A8UCp1I+H/dSFyjwJhp6wta4hsVRhjf8w9qBHRzxYt14RaOcjvQnhD1N4yKOddEjflwMnQM4VtXjQ==",
        deps = {
            "debug": "4.3.4",
            "queue-microtask": "1.2.3",
            "randombytes": "2.1.0",
            "readable-stream": "3.6.0",
            "ws": "7.5.8",
        },
        transitive_closure = {
            "simple-websocket": ["9.1.0"],
            "debug": ["4.3.4"],
            "queue-microtask": ["1.2.3"],
            "randombytes": ["2.1.0"],
            "readable-stream": ["3.6.0"],
            "ws": ["7.5.8"],
            "inherits": ["2.0.4"],
            "string_decoder": ["1.3.0"],
            "util-deprecate": ["1.0.2"],
            "safe-buffer": ["5.2.1"],
            "ms": ["2.1.2"],
        },
    )

    npm_import(
        name = "npm__source-map__0.6.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "source-map",
        version = "0.6.1",
        integrity = "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
        transitive_closure = {
            "source-map": ["0.6.1"],
        },
    )

    npm_import(
        name = "npm__string-width__4.2.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "string-width",
        version = "4.2.3",
        integrity = "sha512-wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==",
        deps = {
            "emoji-regex": "8.0.0",
            "is-fullwidth-code-point": "3.0.0",
            "strip-ansi": "6.0.1",
        },
        transitive_closure = {
            "string-width": ["4.2.3"],
            "emoji-regex": ["8.0.0"],
            "is-fullwidth-code-point": ["3.0.0"],
            "strip-ansi": ["6.0.1"],
            "ansi-regex": ["5.0.1"],
        },
    )

    npm_import(
        name = "npm__string_decoder__1.3.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "string_decoder",
        version = "1.3.0",
        integrity = "sha512-hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==",
        deps = {
            "safe-buffer": "5.2.1",
        },
        transitive_closure = {
            "string_decoder": ["1.3.0"],
            "safe-buffer": ["5.2.1"],
        },
    )

    npm_import(
        name = "npm__strip-ansi__6.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "strip-ansi",
        version = "6.0.1",
        integrity = "sha512-Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==",
        deps = {
            "ansi-regex": "5.0.1",
        },
        transitive_closure = {
            "strip-ansi": ["6.0.1"],
            "ansi-regex": ["5.0.1"],
        },
    )

    npm_import(
        name = "npm__to-regex-range__5.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "to-regex-range",
        version = "5.0.1",
        integrity = "sha512-65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==",
        deps = {
            "is-number": "7.0.0",
        },
        transitive_closure = {
            "to-regex-range": ["5.0.1"],
            "is-number": ["7.0.0"],
        },
    )

    npm_import(
        name = "npm__tr46__0.0.3",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "tr46",
        version = "0.0.3",
        integrity = "sha512-N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==",
        transitive_closure = {
            "tr46": ["0.0.3"],
        },
    )

    npm_import(
        name = "npm__uglify-js__3.16.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "uglify-js",
        version = "3.16.0",
        integrity = "sha512-FEikl6bR30n0T3amyBh3LoiBdqHRy/f4H80+My34HOesOKyHfOsxAPAxOoqC0JUnC1amnO0IwkYC3sko51caSw==",
        transitive_closure = {
            "uglify-js": ["3.16.0"],
        },
        run_lifecycle_hooks = True,
    )

    npm_import(
        name = "npm__uri-js__4.4.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "uri-js",
        version = "4.4.1",
        integrity = "sha512-7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==",
        deps = {
            "punycode": "2.1.1",
        },
        transitive_closure = {
            "uri-js": ["4.4.1"],
            "punycode": ["2.1.1"],
        },
    )

    npm_import(
        name = "npm__util-deprecate__1.0.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "util-deprecate",
        version = "1.0.2",
        integrity = "sha512-EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==",
        transitive_closure = {
            "util-deprecate": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__webidl-conversions__3.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "webidl-conversions",
        version = "3.0.1",
        integrity = "sha512-2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==",
        transitive_closure = {
            "webidl-conversions": ["3.0.1"],
        },
    )

    npm_import(
        name = "npm__whatwg-url__5.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "whatwg-url",
        version = "5.0.0",
        integrity = "sha512-saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==",
        deps = {
            "tr46": "0.0.3",
            "webidl-conversions": "3.0.1",
        },
        transitive_closure = {
            "whatwg-url": ["5.0.0"],
            "tr46": ["0.0.3"],
            "webidl-conversions": ["3.0.1"],
        },
    )

    npm_import(
        name = "npm__wordwrap__1.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "wordwrap",
        version = "1.0.0",
        integrity = "sha512-gvVzJFlPycKc5dZN4yPkP8w7Dc37BtP1yczEneOb4uq34pXZcvrtRTmWV8W+Ume+XCxKgbjM+nevkyFPMybd4Q==",
        transitive_closure = {
            "wordwrap": ["1.0.0"],
        },
    )

    npm_import(
        name = "npm__wrap-ansi__7.0.0",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "wrap-ansi",
        version = "7.0.0",
        integrity = "sha512-YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==",
        deps = {
            "ansi-styles": "4.3.0",
            "string-width": "4.2.3",
            "strip-ansi": "6.0.1",
        },
        transitive_closure = {
            "wrap-ansi": ["7.0.0"],
            "ansi-styles": ["4.3.0"],
            "string-width": ["4.2.3"],
            "strip-ansi": ["6.0.1"],
            "ansi-regex": ["5.0.1"],
            "emoji-regex": ["8.0.0"],
            "is-fullwidth-code-point": ["3.0.0"],
            "color-convert": ["2.0.1"],
            "color-name": ["1.1.4"],
        },
    )

    npm_import(
        name = "npm__wrappy__1.0.2",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "wrappy",
        version = "1.0.2",
        integrity = "sha512-l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==",
        transitive_closure = {
            "wrappy": ["1.0.2"],
        },
    )

    npm_import(
        name = "npm__ws__7.5.8",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "ws",
        version = "7.5.8",
        integrity = "sha512-ri1Id1WinAX5Jqn9HejiGb8crfRio0Qgu8+MtL36rlTA6RLsMdWt1Az/19A2Qij6uSHUMphEFaTKa4WG+UNHNw==",
        transitive_closure = {
            "ws": ["7.5.8"],
        },
    )

    npm_import(
        name = "npm__y18n__5.0.8",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "y18n",
        version = "5.0.8",
        integrity = "sha512-0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==",
        transitive_closure = {
            "y18n": ["5.0.8"],
        },
    )

    npm_import(
        name = "npm__yaml-ast-parser__0.0.43",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "yaml-ast-parser",
        version = "0.0.43",
        integrity = "sha512-2PTINUwsRqSd+s8XxKaJWQlUuEMHJQyEuh2edBbW8KNJz0SJPwUSD2zRWqezFEdN7IzAgeuYHFUCF7o8zRdZ0A==",
        transitive_closure = {
            "yaml-ast-parser": ["0.0.43"],
        },
    )

    npm_import(
        name = "npm__yargs-parser__20.2.9",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "yargs-parser",
        version = "20.2.9",
        integrity = "sha512-y11nGElTIV+CT3Zv9t7VKl+Q3hTQoT9a1Qzezhhl6Rp21gJ/IVTW7Z3y9EWXhuUBC2Shnf+DX0antecpAwSP8w==",
        transitive_closure = {
            "yargs-parser": ["20.2.9"],
        },
    )

    npm_import(
        name = "npm__yargs__17.0.1",
        root_package = "rules_openapi/tools",
        link_workspace = "com_github_scionproto_scion",
        link_packages = {},
        package = "yargs",
        version = "17.0.1",
        integrity = "sha512-xBBulfCc8Y6gLFcrPvtqKz9hz8SO0l1Ni8GgDekvBX2ro0HRQImDGnikfc33cgzcYUSncapnNcZDjVFIH3f6KQ==",
        deps = {
            "cliui": "7.0.4",
            "escalade": "3.1.1",
            "get-caller-file": "2.0.5",
            "require-directory": "2.1.1",
            "string-width": "4.2.3",
            "y18n": "5.0.8",
            "yargs-parser": "20.2.9",
        },
        transitive_closure = {
            "yargs": ["17.0.1"],
            "cliui": ["7.0.4"],
            "escalade": ["3.1.1"],
            "get-caller-file": ["2.0.5"],
            "require-directory": ["2.1.1"],
            "string-width": ["4.2.3"],
            "y18n": ["5.0.8"],
            "yargs-parser": ["20.2.9"],
            "emoji-regex": ["8.0.0"],
            "is-fullwidth-code-point": ["3.0.0"],
            "strip-ansi": ["6.0.1"],
            "ansi-regex": ["5.0.1"],
            "wrap-ansi": ["7.0.0"],
            "ansi-styles": ["4.3.0"],
            "color-convert": ["2.0.1"],
            "color-name": ["1.1.4"],
        },
    )
